### ISSUE TITLE
Filesystem notification support

### ISSUE THREAD

**Issue by jurriaan** [benjaminoakes/maid#116]
This gem looks great, but as mentioned in the README there is no support for running actions whenever files are added/modified.
I would like these features very much and want to help out.

I did some research, and I think the [listen gem](https://github.com/guard/listen) would be a great way to add this feature.

What's the best way to add this to maid? Because if you want to listen to fs changes you have to run a background process looking for those changes.

If there is going to be a maid daemon, maybe you could ditch the whole cron idea and use something like [rufus-scheduler](https://github.com/jmettraux/rufus-scheduler) to make things easier (I think it's confusing to run a daemon for fs changes and having to create cron jobs to schedule the rest).

What do you think? And what about the API for this change?

**Comment by mhalano** [comment]
I think this behavior is perfect. When this patch will be added to code and become a gem?

**Comment by jurriaan** [comment]
@mhalano It was released a few days ago as v0.6.0

**Comment by benjaminoakes** [comment]
Indeed it was.  Unless I'm missing something, it looks like this issue can be closed.
