### ISSUE TITLE
`maid log` would be a convenient way of reading `~/.maid/maid.log`

### ISSUE THREAD

**Issue by brandondrew** [benjaminoakes/maid#143]
It's easier to remember a command than to remember a path, and `maid help` would list `maid log` for those who forgot, so it would be much more convenient to check the maid log by typing `maid log` than by typing something like `cat ~/.maid/maid.log | less`.  It's not so much the extra typing as the need to stop and think "where was the log again???", which would be a distraction from whatever problem you were trying to solve by checking the log in the first place.

**Comment by benjaminoakes** [comment]
I'd be for this (pull requests welcome), though I might prefer printing the path so it could be opened by any program.

**Comment by benjaminoakes** [comment]
Implemented in https://github.com/benjaminoakes/maid/pull/169
