### ISSUE TITLE
Watching directory drains battery when downloading files

### ISSUE THREAD

**Issue by songchenwen** [benjaminoakes/maid#149]
When downloading files, every file modification fires the `watch` rules. This causes high CPU and battery usage. 

I use this method to protect my battery. 

~~~ ruby
	watch('~/Downloads', {wait_for_delay: 10, ignore: [/\.crdownload$/, /\.download$/, /\.aria2$/, /\.td$/, /\.td.cfg$/]}) do
		rule 'Downloads Change' do |modified, added, removed|
			if added.any?()
				newly() 
				movie_in_downloads()
				psd_in_downloads()
			end
		end
	end
~~~

I'm wondering if there is a way to reduce battery usage generally by the `watch` tool itself, not by my rules.

**Comment by benjaminoakes** [comment]
Interesting.  Maybe we should include this by default for `watch` since it seems like sensible default behavior that could be overridden.
