### ISSUE TITLE
cannot locate the maid command file; command not found

### ISSUE THREAD

**Issue by Canorus** [benjaminoakes/maid#161]
Maid worked great at first, but at some point it stopped working. So I tried to find what's the problem and noticed maid is not in the PATH, but not just _not in PATH_ but it's completely gone.

Based on this [issue thread](https://github.com/benjaminoakes/maid/issues/103), I assume `/usr/local/bin/maid` is where it should be. So I thought I mistakenly deleted it and tried to reinstall it, but as you can see below, even after reinstall it's not there where it's supposed to be.

![](http://d.pr/i/15lLt+)

Now I need your help. What should I do to find out what's wrong? Thanks.

**Comment by torrottum** [comment]
Do you use RVM or rbenv?
RVM installs gems to `$HOME/.rvm/{ruby-version}/bin`, not sure about rbenv
You can find the executable directory directory by running `gem env | grep "EXECUTABLE DIRECTORY"`

**Comment by Canorus** [comment]
@torrottum Thanks! Didn't know gems are stored elsewhere. That solved my problem :)

**Comment by benjaminoakes** [comment]
@torrottum Thanks from me too! I was going to say the same thing.

**Comment by torrottum** [comment]
No problem, happy to help! :smile:
