### ISSUE TITLE
Daemon stops responding to fsevents

### ISSUE THREAD

**Issue by dnicolson** [benjaminoakes/maid#163]
The daemon on macOS successfully works (via the Terminal or launchd), but after about an hour the watch rules seem to stop working.

During this time `rb-fsevent` seems to still be running:

`ps -axww | grep ruby`
```
~/.rbenv/versions/2.3.1/bin/ruby ~/.rbenv/versions/2.3.1/bin/maid daemon
~/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rb-fsevent-0.9.8/bin/fsevent_watch --latency 0.1 ~/Downloads
```

In an attempt to debug the file system events, the following command was run at the same time in a different session:
```
require 'rb-fsevent'

fsevent = FSEvent.new
fsevent.watch Dir.pwd do |directories|
  puts "Detected change inside: #{directories.inspect}"
end
fsevent.run
```

After roughly 90 minutes `maid` ceased responding to file system events but in the above `fsevent.watch` continued to respond to events.

**Comment by montchr** [comment]
I might be running into this issue also, on macOS 10.12.2. If I run `maid daemon`, I get the following output:

```
$ maid daemon
Logging actions to "/Users/montchr/.maid/maid.log"
2017-01-15 00:49 fsevent_watch[90689] (FSEvents.framework) FSEventStreamStart: ERROR: FSEvents_connect() => (ipc/send) invalid destination port (268435459)
2017-01-15 00:49 fsevent_watch[90690] (FSEvents.framework) FSEventStreamStart: ERROR: FSEvents_connect() => (ipc/send) invalid destination port (268435459)
2017-01-15 00:49 fsevent_watch[90691] (FSEvents.framework) FSEventStreamStart: ERROR: FSEvents_connect() => (ipc/send) invalid destination port (268435459)
```

The daemon still works, but I think it eventually stops.

**Comment by dnicolson** [comment]
A temporary workaround is to run using launchd with `KeepAlive` set to true and scheduling the process to be killed at regular intervals. In recent testing the daemon stopped responding to events between 35-40 minutes after starting, so the following cron job is used:

`*/30 * * * * /bin/kill $(ps xo pid,ppid,args | grep 'maid daemon' | grep ' 1 ' | awk '{print $1}')`

**Comment by benjaminoakes** [comment]
Does this happen on macOS prior to 10.12?  (I'm still on 10.11 for a variety of reasons.)

**Comment by dnicolson** [comment]
The problem seems to be only affecting one of the rules, the first one which watches the `~/Downloads` directory. Other directory rules (including a subdirectory of `~/Downloads`) continue to be logged to `maid.log` after the `~/Downloads` rule stops working.

I'm not sure why but using the `listen` gem (same version), seems to keep logging events in the `~/Downloads` directory using the following code (which is similar to `watch.rb`):

```
require 'listen'

listener = Listen.to(File.expand_path('~/Downloads')) do |modified, added, removed|
  File.write('listen.log', "added #{added.inspect}\n", mode: 'a')
  File.write('listen.log', "modified #{modified.inspect}\n", mode: 'a')
  File.write('listen.log', "removed #{removed.inspect}\n", mode: 'a')
end
listener.start
sleep
```

**Comment by dnicolson** [comment]
Closing this issue as the `~/Downloads` directory also appears stop responding to events eventually when using the `listen` gem.
