### ISSUE TITLE
Provide rules as parameter

### ISSUE THREAD

**Issue by Canorus** [benjaminoakes/maid#171]
Maybe some rules wants to be run on hourly bases, some on daily bases, some can be monthly basis. However maid only takes only single rule —— `rules.rb`

So I thought maybe it would be much useful if maid takes multiple rules as parameter, i.e. `maid clean --force --silent --rule hourly_rules.rb`

This also will work nice with crontab, such as

```
0 0 1 * * /bin/bash -li -c "maid clean --force monthly_rules.rb"
0 0 * * 0 /bin/bash -li -c "maid clean --force weekly_sunday_rules.rb"
0 3 * * * /bin/bash -li -c "maid clean --force daily_rules.rb"
0 * * * * /bin/bash -li -c "maid clean --force --silent hourly_rules.rb"
```

**Comment by Plloi** [comment]
...it does? Option -r takes a rules files file.
Also from the readme:
`maid clean -fr some_rules.rb  # Run the rules in the file 'some_rules.rb', logging to ~/.maid/maid.log`

**Comment by Canorus** [comment]
oh gee I must have missed it. Thanks for letting me know!
