### ISSUE TITLE
Cannot load other rule files

### ISSUE THREAD

**Issue by yuvgin** [benjaminoakes/maid#172]
Hey, 
Quite new to Ruby so it's possible I'm missing something.
As per the tutorial, I tried to create a second rule file some_rules.rb in my /.Maid/ directory.
However, running the command: 

`maid clean -r some_rules.rb`

Results in the following error:

`cannot load such file -- some_rules.rb`

By the way this is also true for my main rules file using the command `maid clean -r rules.rb` , although `maid clean` works well as expected.

I'm running Mac OS 10.14 (Mojave) with GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18).

Anyone have a hint at what's causing this?

**Comment by Plloi** [comment]
You need the full or relative path to some_rules.rb: `maid clean -r .Maid/some_rules.rb` if run from your home dir (assuming /.Maid/ is actually ~/.Maid/ as it's much saner that way.)

**Comment by yuvgin** [comment]
Cheers, that was it.
How silly of me

**Comment by benjaminoakes** [comment]
@Plloi Thanks for answering 🙂
