### ISSUE TITLE
Update to v0.8.0.beta.1

### ISSUE THREAD

**Issue by benjaminoakes** [benjaminoakes/maid#176]
Thanks to @phylor, there are a bunch of new changes.  I'd like to release this as v0.8.0 after we can verify that things are still working.  The first part of that is releasing a beta, which just involves bumping some versions, etc.  It's been a while since I've done a release, so after those changes are made, I also need to make sure I can release to rubygems.org.

Help with bumping the internal versions and testing would be very appreciated!  I'd also be up for updating dependencies.  We can drop any old Ruby versions that stop working, but if the tests are still passing, I'm fine with keeping them for now.

I'm still using maid, but much less than I used to, so thank you @phylor for making some contributions.

**Comment by anlek** [comment]
Any news on this?

**Comment by benjaminoakes** [comment]
@anlek Nope, will welcome help as described. 😄

**Comment by anlek** [comment]
I haven't used Maid yet but will see what I can do to help test and upgrade to newer version of ruby.
