### ISSUE TITLE
New install on Ruby 2.7.0 through rbenv.

### ISSUE THREAD

**Issue by mistercorea** [benjaminoakes/maid#181]
I am new to ruby and project. When I finished the installation and ran I get following errors.
I ran
`rbnev install 2.7.0 && 
rbenv global 2.7.0
gem install maid`
and added ~/.maid/rules.rb 

> maid
~/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/mime-types-2.99.3/lib/mime/types/logger.rb:26: warning: `_1' is reserved for numbered parameter; consider another name
~/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/mime-types-2.99.3/lib/mime/types/logger.rb:26: warning: `_2' is reserved for numbered parameter; consider another name
~/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/mime-types-2.99.3/lib/mime/types/logger.rb:26: warning: `_3' is reserved for numbered parameter; consider another name

---------------------------
> maid clean --dry-run

Traceback (most recent call last):
	11: from ~/.rbenv/versions/2.7.0/bin/maid:23:in `<main>'
	10: from ~/.rbenv/versions/2.7.0/bin/maid:23:in `load'
	 9: from ~/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/maid-0.7.0/bin/maid:5:in `<top (required)>'
	 8: from ~/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	 7: from ~/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	 6: from ~/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	 5: from ~/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	 4: from ~/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/maid-0.7.0/lib/maid/app.rb:50:in `clean'
	 3: from ~/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/maid-0.7.0/lib/maid/maid.rb:78:in `load_rules'
	 2: from ~/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/maid-0.7.0/lib/maid.rb:28:in `with_instance'
	 1: from ~/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/maid-0.7.0/lib/maid/maid.rb:82:in `block in load_rules'
~/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/maid-0.7.0/lib/maid/maid.rb:82:in `load': ~/.maid/rules.rb:21: syntax error, unexpected end-of-input, expecting `end' (SyntaxError)

**Comment by quintrino** [comment]
Looks like this is related to the mime-types gem
https://github.com/mime-types/ruby-mime-types/pull/146

@benjaminoakes I can see in the gemspec that you kept it locked at mime-types 2 for Ubuntu, but it looks like those comments predate 2018, is that gem lock still valid or can it be updated? 

  s.add_dependency('mime-types', '~> 2.0', '< 3.0') # 3.0 drops Ruby 1.9.3 compatibility (which should be kept for Ubuntu, at least until we document use of Maid on 2.0+ for Ubuntu).  mime-types 2.99 is supported until 2017-11-21.  https://github.com/mime-types/ruby-mime-types/#mime-types-2x-end-of-life

**Comment by benjaminoakes** [comment]
The dependency can likely be unlocked without issue.
